import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle2, KeyRound, ShieldCheck } from 'lucide-react';
import api from '../lib/api';
import PasswordInput from '../components/PasswordInput';

export default function ActivationPage() {
  const [params] = useSearchParams(); const token = params.get('token');
  const [state,setState] = useState({ loading:true, email:'', error:'' }); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false);
  const navigate=useNavigate();
  useEffect(()=>{if(!token){setState({loading:false,error:'Activation token is missing.'});return}api.get(`/auth/activation/${encodeURIComponent(token)}`).then(({data})=>setState({loading:false,email:data.email,error:''})).catch(err=>setState({loading:false,error:err.response?.data?.message||'Activation link is invalid.'}))},[token]);
  const activate=async e=>{e.preventDefault();setBusy(true);setState(s=>({...s,error:''}));try{await api.post('/auth/activate',{token,password});navigate('/login',{replace:true})}catch(err){setState(s=>({...s,error:err.response?.data?.message||'Activation failed.'}))}finally{setBusy(false)}};
  return <div className="activation-page grid min-h-screen place-items-center bg-bg p-5 text-text"><main className="activation-card w-[min(500px,100%)] rounded-3xl border border-line bg-panel p-8 text-center shadow-elevated"><div className="activation-icon">{state.error?<KeyRound/>:<ShieldCheck/>}</div><p className="eyebrow mb-1 text-[var(--font-micro)] font-extrabold uppercase tracking-[var(--tracking-wide)] text-[var(--muted-2)] accent text-accent-contrast">Email verification</p><h1>Activate your account</h1>{state.loading?<p>Checking your secure activation link…</p>:state.error?<><div className="alert mt-4 rounded-xl px-4 py-3 text-small error border border-red/25 bg-red/10 text-red">{state.error}</div><Link className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" to="/login">Return to login</Link></>:<form onSubmit={activate}><div className="verified-email"><CheckCircle2/><span>Email verified for <strong>{state.email}</strong></span></div><p>Confirm the password you selected during signup to activate this workspace.</p><label>Signup password<PasswordInput autoFocus required value={password} onChange={e=>setPassword(e.target.value)}/></label>{state.error&&<div className="alert mt-4 rounded-xl px-4 py-3 text-small error border border-red/25 bg-red/10 text-red">{state.error}</div>}<button className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" disabled={busy}>{busy?'Activating…':'Activate and continue'}</button></form>}</main></div>;
}
