import { useState } from 'react';
import { ArrowLeft,CheckCircle2,Mail } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../lib/api';

export default function ForgotPasswordPage(){
  const [email,setEmail]=useState('');const [result,setResult]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const {data}=await api.post('/auth/forgot-password',{email});setResult(data)}catch(err){setError(err.response?.data?.message||'Unable to request a reset link')}finally{setBusy(false)}};
  return <div className="activation-page grid min-h-screen place-items-center bg-bg p-5 text-text"><main className="activation-card w-[min(500px,100%)] rounded-3xl border border-line bg-panel p-8 text-center shadow-elevated"><div className="activation-icon">{result?<CheckCircle2/>:<Mail/>}</div><p className="eyebrow mb-1 text-[var(--font-micro)] font-extrabold uppercase tracking-[var(--tracking-wide)] text-[var(--muted-2)] accent text-accent-contrast">Account recovery</p><h1>Forgot your password?</h1>{result?<><p>{result.message}</p>{result.developmentResetUrl&&<a className="development-link" href={result.developmentResetUrl}>Open development reset link</a>}<Link className="secondary-button inline-flex min-h-10 items-center justify-center gap-2 rounded-[var(--radius-md)] border border-line bg-transparent px-4 text-small font-bold text-text transition hover:border-accent" to="/login"><ArrowLeft/>Return to login</Link></>:<form onSubmit={submit}><p>Enter your activated account email. We’ll send a secure, single-use reset link.</p><label>Email address<input type="email" required autoFocus value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<div className="alert mt-4 rounded-xl px-4 py-3 text-small error border border-red/25 bg-red/10 text-red">{error}</div>}<button className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" disabled={busy}>{busy?'Sending…':'Send reset link'}</button><Link className="text-back" to="/login"><ArrowLeft/>Back to login</Link></form>}</main></div>;
}
