import { useEffect,useState } from 'react';
import { CheckCircle2,KeyRound } from 'lucide-react';
import { Link,useSearchParams } from 'react-router-dom';
import api from '../lib/api';
import PasswordInput from '../components/PasswordInput';

export default function ResetPasswordPage(){
  const [params]=useSearchParams();const token=params.get('token');const [state,setState]=useState({loading:true,email:'',error:''});const [form,setForm]=useState({password:'',confirmPassword:''});const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!token){setState({loading:false,error:'Password reset token is missing.'});return}api.get(`/auth/password-reset/${encodeURIComponent(token)}`).then(({data})=>setState({loading:false,email:data.email,error:''})).catch(err=>setState({loading:false,error:err.response?.data?.message||'Reset link is invalid.'}))},[token]);
  const strength=passwordStrength(form.password);
  const mismatch=Boolean(form.confirmPassword&&form.password!==form.confirmPassword);
  const submit=async event=>{event.preventDefault();setBusy(true);setState(current=>({...current,error:''}));try{await api.post('/auth/reset-password',{token,...form});setDone(true)}catch(err){setState(current=>({...current,error:err.response?.data?.message||'Password reset failed.'}))}finally{setBusy(false)}};
  return <div className="activation-page grid min-h-screen place-items-center bg-bg p-5 text-text"><main className="activation-card w-[min(500px,100%)] rounded-3xl border border-line bg-panel p-8 text-center shadow-elevated reset-card"><div className="activation-icon">{done?<CheckCircle2/>:<KeyRound/>}</div><p className="eyebrow mb-1 text-[var(--font-micro)] font-extrabold uppercase tracking-[var(--tracking-wide)] text-[var(--muted-2)] accent text-accent-contrast">Secure password reset</p><h1>{done?'Password updated':'Choose a new password'}</h1>{state.loading?<p>Validating your reset link…</p>:done?<><p>Every existing session has been signed out. Use the new password to access Pay-Panda.</p><Link className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" to="/login">Continue to login</Link></>:state.error&&!state.email?<><div className="alert mt-4 rounded-xl px-4 py-3 text-small error border border-red/25 bg-red/10 text-red">{state.error}</div><Link className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" to="/forgot-password">Request another link</Link></>:<form onSubmit={submit}><p>Resetting password for <strong>{state.email}</strong>. This link can only be used once.</p><label>New password<PasswordInput minLength="6" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="password-strength mt-2"><div className="strength-track h-1.5 overflow-hidden rounded-full bg-line"><i style={{width:`${strength.score*25}%`}} className={`strength-${strength.score}`}/></div><div><span>{strength.label}</span><small>Minimum 6 characters; mixed characters improve strength</small></div></div><label>Confirm new password<PasswordInput className={mismatch?'input-invalid':''} minLength="6" required value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/>{mismatch&&<span className="field-error mt-1 block text-small text-red">Passwords do not match.</span>}</label>{state.error&&<div className="alert mt-4 rounded-xl px-4 py-3 text-small error border border-red/25 bg-red/10 text-red">{state.error}</div>}<button className="primary-button inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] border-0 bg-gradient-to-br from-violet-600 to-indigo-500 px-4 font-bold text-white shadow-[var(--shadow-glow-accent)] transition disabled:cursor-not-allowed disabled:opacity-60" disabled={busy||mismatch}>{busy?'Updating…':'Reset password'}</button></form>}</main></div>;
}

function passwordStrength(value){if(!value)return{score:0,label:'Enter a secure password'};let score=0;if(value.length>=6)score++;if(/[a-z]/.test(value)&&/[A-Z]/.test(value))score++;if(/\d/.test(value))score++;if(/[^A-Za-z\d]/.test(value)&&!/\s/.test(value))score++;return{score,label:['Very weak','Weak','Fair','Good','Strong'][score]}}
